---
steps:
- name: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    # Get list of directories to loop over
    for dir in "${array[@]}"; do
        echo "$dir"
    done
    # for loop: docker build {@dir}
        # if gcr.io/{PROJECT_ID}/image tag  == dockerfile hash
            # skip this build and continue
        #docker build -t gcr.io/${PROJECT_ID}/{directory name}:{dockerfile hash} -f {directory name}/Dockerfile .
        #docker push gcr.io/${PROJECT_ID}/{directory name}:{dockerfile hash}


# - name: 'gcr.io/cloud-builders/docker'
#  args:
#    - 'build'
#    - '--tag=gcr.io/${PROJECT_ID}/gobuster:latest'
#    - '--file=gobuster/Dockerfile'
#    - '.'
# - name: 'gcr.io/cloud-builders/docker'
#  args:
#    - 'build'
#    - '--tag=gcr.io/${PROJECT_ID}/tshark:latest'
#    - '--file=tshark/Dockerfile'
#    - '.'
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'build'
#     - '--tag=gcr.io/${PROJECT_ID}/beef:latest'
#     - '--file=beef/Dockerfile'
#     - '.'
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'build'
#     - '--tag=gcr.io/${PROJECT_ID}/beef:latest'
#     - '--file=beef/Dockerfile'
    # - '.'
#images:
    # - 'gcr.io/${PROJECT_ID}/gobuster:latest'
    # - 'gcr.io/${PROJECT_ID}/tshark:latest'
    # - 'gcr.io/${PROJECT_ID}/beef:latest'
