---
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    # Get list of directories to loop over
    array=(*/)
    dir_count=1
    for dir in "${array[@]}"; do
        echo "Building $dir_count/${#array[@]}"
        # Trim the trailing / from the name
        toolname=${dir:0:(-1)}
        dockerfile_dir="$(echo $dir)Dockerfile"
        dockerfile_md5=$(md5sum ${dir}Dockerfile | cut -d ' ' -f1)

        echo "Checking for existing image for tool: $toolname with Dockerfile md5 hash of: $dockerfile_md5"
        existing_tags=$(gcloud container images list-tags --filter="tags:$dockerfile_md5" --format=json gcr.io/$PROJECT_ID/$toolname)
        is_existing_tags_empty=$(echo "$existing_tags" | wc -c)
        echo "test: $is_existing_tags_empty"
        if [ $is_existing_tags_empty -lt 4 ]; then
            echo "Empty return because 2 characters = [] (big assumption)"
        fi

        # Increment counter
        ((dir_count=dir_count+1))
    done
    # for loop: docker build {@dir}
        # if gcr.io/{PROJECT_ID}/image tag  == dockerfile hash
            # skip this build and continue
        #docker build -t gcr.io/${PROJECT_ID}/{directory name}:{dockerfile hash} -f {directory name}/Dockerfile .
        #docker push gcr.io/${PROJECT_ID}/{directory name}:{dockerfile hash}


# - name: 'gcr.io/cloud-builders/docker'
#  args:
#    - 'build'
#    - '--tag=gcr.io/${PROJECT_ID}/gobuster:latest'
#    - '--file=gobuster/Dockerfile'
#    - '.'
# - name: 'gcr.io/cloud-builders/docker'
#  args:
#    - 'build'
#    - '--tag=gcr.io/${PROJECT_ID}/tshark:latest'
#    - '--file=tshark/Dockerfile'
#    - '.'
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'build'
#     - '--tag=gcr.io/${PROJECT_ID}/beef:latest'
#     - '--file=beef/Dockerfile'
#     - '.'
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'build'
#     - '--tag=gcr.io/${PROJECT_ID}/beef:latest'
#     - '--file=beef/Dockerfile'
    # - '.'
#images:
    # - 'gcr.io/${PROJECT_ID}/gobuster:latest'
    # - 'gcr.io/${PROJECT_ID}/tshark:latest'
    # - 'gcr.io/${PROJECT_ID}/beef:latest'
